#!/usr/bin/env bash

WALLPAPER="/usr/share/endeavouros/backgrounds/explore.jpg"
#!/usr/bin/env bash

alpha='dd'
background='#282828'
selection='#504945'
comment='#ebdbb2'

yellow='#fabd2f'
orange='#fe8019'
red='#fb4934'
magenta='#d3869b'
blue='#83a598'
cyan='#8ec07c'
green='#b8bb26'

i3lock \
  --insidever-color=$selection$alpha \
  --insidewrong-color=$selection$alpha \
  --inside-color=$selection$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$magenta$alpha \
  --line-uses-ring \
  --keyhl-color=$blue$alpha \
  --bshl-color=$orange$alpha \
  --separator-color=$selection$alpha \
  --verif-color=$green \
  --wrong-color=$red \
  --modif-color=$red \
  --layout-color=$orange \
  --date-color=$orange \
  --time-color=$orange \
  --clock \
  --indicator \
  --time-str="%H:%M:%S" \
  --date-str="%Y - %m - %d" \
  --verif-text="Checking..." \
  --wrong-text="Wrong pswd" \
  --noinput="No Input" \
  --lock-text="Locking..." \
  --lockfailed="Lock Failed" \
  --time-pos="500:200" \
  --date-pos="500:240" \
  --ind-pos="500:540" \
  --radius=120 \
  --ring-width=10 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
  --image="$WALLPAPER" \
  --fill \
 # --screen 1 \
  # --blur 1 \
#  --time-font="JetBrainsMono Nerd Font" \
#  --date-font="JetBrainsMono Nerd Font" \
#  --layout-font="JetBrainsMono Nerd Font" \
#  --verif-font="JetBrainsMono Nerd Font" \
#  --wrong-font="JetBrainsMono Nerd Font" \

# These last five lines are commented because they concern the font you want to use.
# JetBrainsMono Nerd Font is the font that was used in the screenshot.
# To specify a favorite font, just uncomment the five lines and replace the parameter with the font you prefer.
